name: tr38back
favicon: null
layout_spectrum: 0.7085695583373308
typography_spectrum: 0.49298792867921293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4385890329722315
  lightness: 0.3714563148096204
  saturation: 0.5313319270499051
  rhythmicContrast: 0.028935505310073495
purpose: []
